project:
  type: website

website:
  title: "Visual Analytics"
  page-navigation: true
  reader-mode: true
  navbar:
    collapse: true
    left:
    - icon: linkedin
      href: https://www.linkedin.com/in/junseokkim1/
    - icon: github
      href: https://github.com/junsok21
    
    right:
    - icon: person-square
      text: "Hands-on Exercise"
      menu:
      - text: "Hands-on Exercise1"
        href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
      - text: "Hands-on Exercise2"
        href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
      - text: "Hands-on Exercise3"
        href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
      - text: "Hands-on Exercise4"
        href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
    - icon: person-square
      text: "In-class Exercise"
      menu: 
          - text: "In-class Exercise1"
            href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
          - text: "In-class Exercise3"
            href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html"
          - text: "In-class Exercise4"
            href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html"
          - text: "In-class Exercise5"
            href: "In-class_Ex/In-class_Ex05/In-class_Ex05.html"
    - icon: graph-up
      text: "Take-home Exercise"
      menu:
      - text: "Take-home Exercise1"
        href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
      - text: "Take-home Exercise2"
        href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"
      - text: "Take-home Exercise3"
        href: "Take-home_Ex/Take-home_Ex03/Take-home_Ex03.html"
      - text: "Take-home Exercise4"
        href: "Take-home_Ex/Take-home_Ex04/Take-home_Ex04.html"
 
format:
  html:
    code-fold: true
    code-summary: "Show the code"
    theme: lumen
    css: styles.css
    toc: true

editor: visual

