---
title: "Take-home_Ex01"
author: "Junseok K."
---

Install R Packages

```{r}
pacman:: p_load(ggplot2, ggiraph, ggstatsplot, rstatix, gt, patchwork, tidyverse, patchwork, ggdist, png, gganimate, dplyr, skimr, knitr, rstatix, gt)
```


Load the Data

```{r}
Parts <- read_csv("data/Participants.csv")
```

```{r}
Fin <- read_csv("data/FinancialJournal.csv")
```
Data Prep

#Make EducationLevel, interestGroup, category, and Household Size as Factors



```{r}
#| code-fold: true
#| code-summary: "Show code"

Parts <- Parts %>%
  mutate(educationLevel = as.factor(educationLevel))

Parts <- Parts %>%
  mutate(householdSize = as.factor(householdSize))

Parts <- Parts %>%
  mutate(interestGroup = as.factor(interestGroup))

Parts <- Parts %>%
  mutate(participantId = as.integer(participantId))

Fin <- Fin %>%
  mutate(category = as.factor(category))
```


#DateTime transformation


```{r}
Fin$Month_Yr <- format(as.Date(Fin$timestamp), "%Y-%m")
```


#Pivot Columns

```{r}
Fin_Final <- Fin %>%
  group_by(participantId, category) %>%
  summarise(amount = sum(amount)) %>%
  pivot_wider(names_from = category, values_from = amount)
  
```
#Change NA to 0

```{r}
Fin_Final[is.na(Fin_Final)] <- 0
```


#Add new columns
```{r}
Fin_Final <- Fin_Final %>%
   mutate(Cost_of_living = Education + Food + Recreation + Shelter)

Fin_Final <- Fin_Final %>%
   mutate(Total_Income = Wage + RentAdjustment)

Fin_Final <- Fin_Final %>%
   mutate(Total_Savings = Cost_of_living + Total_Income)

```


#Combine 2 tables together

```{r}
combined_table <- merge(Parts, Fin_Final, by = "participantId")
```

```{r}
kable(head(combined_table), "simple")
```

```{r}
skimr::skim(combined_table)
```


```{r}
ggplot(combined_table,
       aes(sample=Total_Savings)) +
  stat_qq()
  stat_qq_line()
```

```{r}
qq <- ggplot(combined_table,
             aes(sample=Total_Savings)) +
  stat_qq() +
  stat_qq_line()

sw_t <- combined_table %>%
  shapiro_test(Total_Savings) %>%
  gt()

tmp<- tempfile(fileext = '.png')
gtsave(sw_t, tmp)
table_png <- png::readPNG(tmp,native = TRUE)

qq + table_png
```


```{r}

```

